In [ ]:
from google.colab import drive
drive.mount('/content/drive')

numpy


In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3,4,5])
print(x)
print(type(x))
# x=np.array([])
print(x.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [ ]:
y=[1,2,3,4]
print(y)
print(type(y))
# %timeit
# %%timeit

[1, 2, 3, 4]
<class 'list'>


In [ ]:
%timeit [j**4 for j in range(1,9)]

2.59 µs ± 42.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit np.arange(1,9)**4

2.25 µs ± 75.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
np.arange(1,9)**4

array([   1,   16,   81,  256,  625, 1296, 2401, 4096])

In [ ]:
p=[1,2,3,4]
q=np.array(p)
print(q)
print(q.ndim)
print(p)

[1 2 3 4]
1
[1, 2, 3, 4]


In [ ]:
#l.append(int_1) 1 with 2=> 1.append(2)
l=[]
for i  in range(1,5):
  int_1=int ( input("enter"))
  l.append(int_1)
  print(np.array(l))

In [ ]:
ar2=np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [ ]:
arr3=np.array([[[1,23,3,4],[1,2,3,4],[1,2,3,4]]])
print (arr3)
print(arr3.ndim)

[[[ 1 23  3  4]
  [ 1  2  3  4]
  [ 1  2  3  4]]]
3


In [ ]:
arr10=np.array( [1,2,3,4],ndmin = 10)
print(arr10)
print(arr10.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [ ]:
ar0=np.zeros(4)
ar00=np.zeros((3,4))
print(ar0)
print(ar00)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ar11=np.ones(4)
print(ar11)

[1. 1. 1. 1.]


In [ ]:
arem=np.empty(4)
print(arem)

[1. 1. 1. 1.]


In [ ]:
s=np.arange(5)
print(s)

[0 1 2 3 4]


In [ ]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
d=np.eye(3,5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
ar_lin=np.linspace(1,10,num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
e=np.random.rand(4)
print(e)

[0.54452543 0.5224541  0.19816975 0.63987654]


In [ ]:
f=np.random.rand(2,6)
print(f)

[[0.02055392 0.83038633 0.3595     0.24584347 0.07067588 0.89813295]
 [0.66755772 0.1704562  0.68183809 0.73799688 0.95479804 0.51212323]]


In [ ]:
g=np.random.randn(5)
print(g)

[ 0.1496304  -0.1866803  -2.27309068  0.12795026  0.63937555]


In [ ]:
d=np.random.ranf(4)
print(d)

[0.9701053  0.66924156 0.61918337 0.68930414]


In [ ]:
k=np.random.randint(5,20,4)
print(k)

[17 12 10 17]


In [ ]:

import numpy as np
a=np.array([1,2,3],dtype=np.int8)
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int8


In [ ]:
a=np.array([1,2,3])
n = np.float32(a)
print(type(a))
print(type(n))
print(a.dtype)
print(n)
#,dtype=np.int8


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int64
[1. 2. 3.]


In [ ]:
a=np.array([1,2,3])
b=a.astype(float)
print(b)


[1. 2. 3.]


In [ ]:
aa=np.array([1,2,3,4])
v=aa+3
print(v)

[4 5 6 7]


In [ ]:
a=np.array([1,2,3,4,5])
c=np.array([1,2,3,4,5])
k=a+c
i=np.add(a,c)
p=a-c
o=a*c
l=a/c
print(i)
print(k)
print(p)
print(o)
print(l)

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]


In [ ]:
var=np.array([[1,2,3],[1,2,3,]])
n=np.reciprocal(var)
print(n)

var2=np.array([[1,2,3],[1,2,3,]])
va=np.add(var,var2)
print(va)

[[1 0 0]
 [1 0 0]]
[[2 4 6]
 [2 4 6]]


In [ ]:
# np.min()
# np.max()
# np.sqrt()
# np.sin()
# np.cos()
# np.argmin()
# np.cumsum()

In [ ]:
b=np.array([1,2,3,4,5])
print(np.argmin(b),np.min(b))

0 1


In [ ]:
var2=np.array([[1,2,3],[1,2,3,]])
print(np.min(var2,axis=0))
print(np.cumsum(var2))

[1 2 3]
[ 1  3  6  7  9 12]


In [ ]:
var2=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
# print(var2[0,2])
for i in np.nditer(var2,flags=['buffered'],op_dtypes=["S"]):
  print(i)

# for i in var2:
#  for l in i:
#    print(l)
print(var2.shape)

b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'
(1, 3, 4)


In [ ]:
n1=np.array([1,2,3,4,5,6])
print(n1[1])


ga = n1.reshape(3,2)
print(ga)
h=ga.reshape(-1)
print(h)

2


TypeError: Field elements must be 2- or 3-tuples, got ''s''

In [ ]:
m=np.array([1,2,3])
m1=np.array([[1],[2],[3]])
print(m1)
print(m+m1)


[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
var2=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
# print(var2[0,2])
for i,d in np.ndenumerate(var2):
  print(i,d)


(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 3
(0, 2, 3) 4


In [ ]:
a=np.array([1,2,3,4,5])
b=a.copy()
v=a.view()
# view=&
print(v)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 1 2 3 4 5]


In [ ]:
a=np.array([[1,2],[4,5]])
b=np.array([[1,2],[4,5]])
c=np.concatenate((a,b),axis=1)
print(c)
c=np.concatenate((a,b),axis=0)
print(c)
d=np.stack((a,b),axis=0)
e=np.vstack((a,b))
print(d)
print(e)

[[1 2 1 2]
 [4 5 4 5]]
[[1 2]
 [4 5]
 [1 2]
 [4 5]]
[[[1 2]
  [4 5]]

 [[1 2]
  [4 5]]]
[[1 2]
 [4 5]
 [1 2]
 [4 5]]


In [ ]:
a=np.array([1,2,3,4,5,6])
x=np.array_split(a,3)
print(x)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
a=np.array([[1,2],[4,5],[5,6]])
j=np.array_split(a,3)
print(j)

[array([[1, 2]]), array([[4, 5]]), array([[5, 6]])]


In [ ]:
a=np.array([1,2,3,4,2,6])
b=np.where(a == 2 )
print(b)

(array([1, 4]),)


In [ ]:
a=np.array([1,2,3,4,6])
v=np.searchsorted(a,5,side="left")
print(v)

4


In [ ]:
a=np.array([1,2,3,4,2,6])
print(np.sort(a))

[1 2 2 3 4 6]


In [ ]:
a=np.array([1,2,3,4])
f=[True,False,True,False]
w1=a[f]
print(w1)

[1 3]


In [ ]:
# shuffle
# unique
# resize
# flatten
# ravel

In [ ]:
a=np.array([1,2,3,4])
np.random.shuffle(a)
print(a)

[1 2 4 3]


In [ ]:
a=np.array([1,2,3,4,5,1,2])
v=np.unique(a,return_index=True,return_counts=True)
print(v)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4]), array([2, 2, 1, 1, 1]))


In [ ]:
a=np.array([1,2,3,4,5,1])
n=np.resize(a,(2,3))
print(n)

[[1 2 3]
 [4 5 1]]


In [ ]:
a=np.array([1,2,3,4,5,1])
print(a.flaten(order="F"))


In [ ]:
a=np.array([1,2,3,4,5,1])
print(np.reval(a,order='y'))

In [ ]:
a=np.array([1,2,3,4])
c=np.insert(a,4,40)
x=np.append(a,6.3)
l=np.delete(a,2)
print(c)
print(x)
print(l)

[ 1  2  3  4 40]
[1.  2.  3.  4.  6.3]
[1 2 4]


In [ ]:
a=np.matrix([[1,2],[4,5]])
b=np.matrix([[1,2],[4,5]])
print(a+b)
print(a-b)
print(a.dot(b))
print(a*b)
print(type(a))
print(np.transpose(a))
print(a.T)

[[ 2  4]
 [ 8 10]]
[[0 0]
 [0 0]]
[[ 9 12]
 [24 33]]
[[ 9 12]
 [24 33]]
<class 'numpy.matrix'>
[[1 4]
 [2 5]]
[[1 4]
 [2 5]]


In [ ]:
# np.transpose
# np.swapaxes
# inverse
# power
# determinate

In [ ]:
b=np.matrix([[1,2],[4,5]])
print(np.swapaxes(b,0,1))
print(np.linalg.inv(b))
print(np.linalg.matrix_power(b,2))
print(np.linalg.matrix_power(b,0))
print(np.linalg.matrix_power(b,-2))
print(b)

[[1 4]
 [2 5]]
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
[[ 9 12]
 [24 33]]
[[1 0]
 [0 1]]
[[ 3.66666667 -1.33333333]
 [-2.66666667  1.        ]]
[[1 2]
 [4 5]]


In [ ]:
b=np.matrix([[1,2],[4,5]])
print(np.linalg.det(b))

-2.9999999999999996
